"""Practical, kind relationship advice — 100+ in each language."""

FA: list[str] = [
    "امروز سه چیز که پارتنرت رو زیبا می‌کنه، با صدای بلند بهش بگو. 💬",
    "گوشی رو کنار بگذار و فقط ۱۰ دقیقه به حرف‌هاش گوش کن — بدون جواب دادن. 🎧",
    "یه پیام صبحگاهی غافلگیر‌کننده بفرست، حتی اگر اون شب کنارته. ☕",
    "از خاطره‌ای که با هم دارید بگو و بپرس «اون لحظه چه حسی داشتی؟» 🎞",
    "یه چیز کوچیک از کارهای روزانه‌ش رو امروز خودت انجام بده. 🧺",
    "بدون منت، فقط بنویس «بدون تو زندگیم سخت‌تر بود». 📝",
    "امشب گوشی‌ها رو خاموش کنید و ۳۰ دقیقه فقط با هم باشید. 📵",
    "یه آهنگ جدید پیدا کن که یاد اون بیفته و بفرستش. 🎶",
    "از یه ترسش حرف بزنید و بهش قول بدید کنارش هستید. 🤝",
    "وقتی عصبانی شدی، قبل از حرف زدن سه نفس عمیق بکش. 🌬️",
    "یه «ممنون» ساده برای کارهایی که بدیهی فرض می‌کنی، بهش بگو. 🙏",
    "یه برنامه کوچیک برای آخر هفته بچینید — حتی پیاده‌روی محله. 🚶",
    "وقتی داره حرف می‌زنه چشم تو چشمش بشو — موبایل دستت نگیر. 👀",
    "از رؤیاهای بلندمدتش بپرس و یه یادداشت ازش بساز. 📓",
    "یه اشتباه کوچیک خودت رو امروز بپذیر و عذرخواهی کن. 🙇",
    "هر بار که از در میای، اول لبخند بزن — تن صدای خونه رو می‌سازی. 😊",
    "از خانواده‌ی پارتنرت یه چیز قشنگ بگو. 👨‍👩‍👧",
    "اگه پارتنرت خسته‌ست، فقط بغلش کن — هیچ توصیه‌ای نده. 🤗",
    "یه چیز جدید با هم یاد بگیرید — یه دستور پخت، یه کلمه‌ی زبان نو. 🍳",
    "هر هفته یه «شب خاطرات» بگذارید و عکس‌های قدیمی ببینید. 🖼",
    "وقتی دعوا شد، اول مسأله رو بنویس، بعد حرف بزن. ✍️",
    "از خود واقعیت تعریف کن — نه ایده‌آلی که نیستی. 🪞",
    "یه چالش کوچیک با هم بسازید: مثلاً ۳۰ روز یه کار سالم. 💪",
    "یه چیزی که از پارتنرت یاد گرفتی، براش تعریف کن. 📚",
    "هیچ پیامی رو بدون فکر نفرست — یه دقیقه صبر کن. ⏳",
    "تنهایی خودت رو مقدس بدون — بعد بهتر می‌تونی عاشق باشی. 🧘",
    "وقتی ناراحته، نگو «درست می‌شه» — فقط بشنو. 👂",
    "یه چیز قشنگ بپز که می‌دونی دوستش داره. 🍲",
    "از یه ضعفت با اعتماد به نفس حرف بزن. 💎",
    "یه عکس قدیمی پیدا کن و بفرست «یادته اون روز؟» 📸",
    "حقیقت رو بگو، حتی اگه نازک باشه — اما مهربون. 🕊",
    "یه «نه» محترمانه بهتر از یه «بله» نصفه‌ست. ✅",
    "پولِ مشترک رو شفاف نگه دارید — هیچ راز مالی‌ای نداشته باشید. 💰",
    "اگر اخیراً نخندیدید، یه استند‌آپ کمدی با هم تماشا کنید. 😂",
    "یه شب رو کاملاً «بدون موبایل» بگذارید. 🌙",
    "اگر دلتنگشی، بهش بگو — هیچ‌چیز قشنگ‌تر از «دلم برات تنگ شده» نیست. 💌",
    "نگرانی‌هات رو با کلمات کوتاه بگو، نه با تن صدای بلند. 🎚",
    "روزی یه چیز جدید درباره‌ی پارتنرت کشف کن. 🔎",
    "حتی توی شلوغی، یه نگاه بهش بنداز که بفهمه می‌بینیش. 👁",
    "از مرز‌هات بگو — احترام بدون شفافیت ساخته نمی‌شه. 🚧",
    "نقاط قوت پارتنرت رو پیش دوستات هم بگو. 🔊",
    "یه «نقد» سازنده با یه «تقدیر» شروع کن. 🥪",
    "وقتی برنامه می‌چینی، نظر اون رو هم جدی بپرس. 🗓",
    "از احساس‌های قبلی‌ت بدون قضاوت بگو — این صداقته. 🪶",
    "هیچ‌وقت با موضع «بُرد-باخت» وارد دعوا نشو. 🤝",
    "یه فهرست کوچیک از چیزهایی که با هم می‌خواید بسازید، تهیه کنید. 📋",
    "یه عادت قشنگ مشترک بسازید — مثل قهوه‌ی صبح. ☕",
    "گاهی فقط حضور کافی‌ست — لازم نیست همیشه راه‌حل بدی. 🌿",
    "از روزی که اولین بار همدیگه رو دیدید، یه چیز جزئی بگو. 🌟",
    "اگر اشتباه کردی، سریع و بدون تبصره عذرخواهی کن. 🙇‍♀️",
    "یه ساعت در هفته رو فقط برای «گفت‌و‌گوی عمیق» بگذارید. 🕐",
    "وقتی رابطه‌تون توی دست‌انداز افتاد، یه شام بیرون برید — تغییر مکان جادو می‌کنه. 🍽",
    "اگه روزی فاصله افتاد، اولین قدم رو خودت بردار. 👣",
    "از یه آرزوی کوچیک پارتنرت پیگیری کن و سورپرایزش کن. 🎁",
    "یه ضعف مشترک‌تون رو پیدا کنید و باهم باهاش بجنگید. 🥊",
    "وقتی داری حرف می‌زنی، نَفسش رو ببین — یاد می‌گیری چه وقت ناراحته. 🌬",
    "احساسات بد رو سرکوب نکن — اما با مهربونی بگو. 🌧",
    "از یه چیز معمولی‌ تعریف کن: «امروز چه قشنگ راه می‌رفتی». 💃",
    "اگه فکر می‌کنی نمی‌فهمدت، اول دست خودت رو امتحان کن: واضح گفتی؟ 🗣",
    "هیچ رابطه‌ای بدون «بازخورد» رشد نمی‌کنه. 📈",
    "یه شب «بدون توقع» بساز — فقط بودن. 🌌",
    "تو رابطه، «همیشه برنده شدن» بدترین باخت ممکنه. 🏳️",
    "وقتی خبر بدی می‌گیرد، اول بغلش کن. بعد سؤال بپرس. 🤗",
    "از علاقه‌مندیش حمایت کن، حتی اگه برات جذاب نباشه. 🎨",
    "یه کلید «جادویی» بسازید: یه کلمه که وقتی هر کدوم گفت، یعنی «خسته‌ام، مهربون باش». 🔑",
    "هر هفته یه دستاورد کوچیک‌تون رو جشن بگیرید. 🥂",
    "حتی وقتی نمی‌فهمی چرا غمگینه، فقط بهش بگو «حقت داری». 💧",
    "یه دفترچه‌ی مشترک خاطرات تهیه کنید — جای انرژی مثبت. 📔",
    "اگه «جنگ سرد» شد، اولین کسی باش که برف رو آب می‌کنه. ❄️➡️💧",
    "گاهی فقط یه ماساژ ۵ دقیقه‌ای پاها، رابطه رو احیا می‌کنه. 💆",
    "از مسؤولیت‌هات تو رابطه فرار نکن — مسؤولیت = عشق. 🧱",
    "یه «نه» به یه جلسه‌ی کاری بزن و یه «بله» به یه شام عاشقانه. ❤️",
    "از یه چیز خنده‌دار که پارتنرت می‌گه فیلم بگیر — این خاطره‌ی طلایی می‌شه. 🎥",
    "تو شب‌های سخت، فقط بنویس «من اینجام» — همین کافیه. ✍️",
    "هیچ مقایسه‌ای با هیچ رابطه‌ی دیگه‌ای نکن — هر رابطه یه ‌نسخه‌ست. 📕",
    "بدی‌های قدیمی رو بایگانی کن، نه سر سفره‌ی هر دعوا. 📦",
    "یه «روز پارتنرت» راه بنداز: ماه یه روز فقط طبق خواسته‌های اون. 🎉",
    "اگه چیزی توی ذهنت چرخه می‌خوره، توی نامه بنویس — بعد بفرست یا بسوزون. 📜",
    "وقتی مهمون داری، پارتنرت رو اول معرفی کن — احساس مهم بودن بده. 🌟",
    "از اون چیزی بپرس که فکر می‌کنی هیچ‌وقت ازش سؤال نشده. 🌀",
    "یه عکس از خنده‌ش بگیر — این می‌شه نسخه‌ی نجاتت تو روزای بد. 📸",
    "اگه شب‌ها فکرت بهم می‌ریزه، با خودت قرار بگذار صبح حرف می‌زنی. 🌙",
    "هیچ متن منفی‌ای رو شب نفرست — صبح، تن صدا تغییر می‌کنه. 🌅",
    "وقتی مریضه، حتی یه چای ساده، یه قصه از عشقه. 🍵",
    "از خاطره‌ی شیرین مشترک‌ به عنوان «لنگر» استفاده کن وقتی غم اومد. ⚓",
    "هر روز ۳ ساعت رو بدون کار، فقط با هم بگذرونید. ⏱",
    "اگه چیزی توی رابطه آزارت می‌ده، روزش بگو — نه ماه بعدش. ⚡",
    "یه «جعبه‌ی پیامک‌های قدیمی» داشته باشید — یه نوع آرشیو عشق. 💌",
    "تو زمان دعوا، از «تو همیشه...» استفاده نکن، از «من حس می‌کنم...» استفاده کن. 🗣",
    "اگه پارتنرت ساکته، نگرانش نباش — بهش فضا بده. ☁️",
    "از یه چیز جدید با هم ترسیدن (مثلاً ترن هوایی) رابطه رو محکم می‌کنه. 🎢",
    "یه‌کاری کن که توی این هفته یه‌بار «خنده‌ی از ته دل» بشنوی. 🤣",
    "اگه هدفش پیشرفت کرد، اون رو بیشتر از خودت جشن بگیر. 🥳",
    "وقتی غم می‌خوره، یه نوشیدنی گرم بیار — کلمات لازم نیست. ☕",
    "اگه می‌خوای امروزش رو خراب نکنی، یه‌بار قبل از حرف زدن، خود رو از بیرون نگاه کن. 🪞",
    "از یه چیز تو وجود خودت که بهش مدیونی، تشکر کن. 🙏",
    "هر چند وقت یه‌بار، نقش‌ها رو عوض کن — مثلاً امروز اون رئیس برنامه‌ست. 👑",
    "وقتی توی رابطه ساکت شدی، فقط بنویس «نمی‌دونم چی بگم، ولی هستم». 🤍",
    "اگه می‌خوای یه چیزی عوض شه، اول از خودت شروع کن. 🌱",
    "یاد بگیر «نمی‌دونم» رو با اعتماد به نفس بگی. 🤷",
    "نتیجه‌ی هر دعوا باید این باشه: ما هر دو رو یه قدم نزدیک‌تر کرد. 🤝",
    "هر شب قبل خواب، یه «شکر» رو با هم تقسیم کنید. 🌌",
    "وقتی مهمونی هستید، هر چند دقیقه یه‌بار نگاهش کن — انگار اولین بار می‌بینیش. 👀",
    "از یه ضعف قدیمی‌ت که بهش غلبه کردی بگو، تا انگیزه‌ای برای اون بشه. 💪",
    "هر روز یه ۱۰ ثانیه‌ی «بغل ساکت» داشته باشید. 🤗",
    "اگر می‌خوای مرز بسازی، با مهربونی بگو — مرز با خشم ساخته نمی‌شه. 🚪",
    "یه «شب فیلم» با ژانر مورد علاقه‌ی اون داشته باشید — حتی اگه دوست نداری. 🎬",
    "هر کلمه‌ای از پارتنرت یاد گرفتی، یه روز ازش استفاده کن. 🗝",
    "از خاطره‌ی بد قدیمی پلی نساز برای هر دعوا. 🚧",
]


EN: list[str] = [
    "Today, name three things that make your partner beautiful and say them out loud. 💬",
    "Put your phone down and *listen* for ten minutes — no replies. 🎧",
    "Send a surprise good-morning text, even if you're together that night. ☕",
    "Bring up a shared memory and ask, 'How did you feel in that moment?' 🎞",
    "Take one small task off their plate today, no announcement needed. 🧺",
    "Write, with no agenda: 'Life would be harder without you.' 📝",
    "Tonight, phones off for 30 minutes — just be together. 📵",
    "Find a new song that reminds you of them and send it. 🎶",
    "Ask them about a fear, and promise to be there for it. 🤝",
    "When you're upset, take three deep breaths before speaking. 🌬️",
    "Thank them for something you usually take for granted. 🙏",
    "Plan one tiny weekend ritual — even just a neighborhood walk. 🚶",
    "Eye contact when they speak — phones away. 👀",
    "Ask about their long-term dream and jot it down. 📓",
    "Own a small mistake today and apologize first. 🙇",
    "Smile when you walk through the door — you set the home's tone. 😊",
    "Compliment something about their family genuinely. 👨‍👩‍👧",
    "If they're tired, just hug them. Skip the advice. 🤗",
    "Learn one new thing together — a recipe, a foreign word. 🍳",
    "Make a weekly 'memory night' with old photos. 🖼",
    "In an argument, write down the issue first, then talk. ✍️",
    "Praise the real you — not the ideal you aren't. 🪞",
    "Build a tiny challenge together: 30 days of one healthy habit. 💪",
    "Tell them one thing you've learned from them. 📚",
    "Don't send messages without thinking — wait one minute. ⏳",
    "Honor your solitude — you love better when you're whole. 🧘",
    "When they're sad, skip 'it'll be okay' — just listen. 👂",
    "Cook something you know they love. 🍲",
    "Talk about one weakness with confidence. 💎",
    "Find an old photo and send: 'Remember that day?' 📸",
    "Tell the truth even when it's fragile — but kindly. 🕊",
    "A respectful 'no' beats a half-hearted 'yes'. ✅",
    "Keep shared money transparent — no financial secrets. 💰",
    "If you haven't laughed lately, watch stand-up together. 😂",
    "Take one night totally 'no-phone'. 🌙",
    "If you miss them, say so — nothing beats 'I miss you'. 💌",
    "Voice worries with short words, not loud tones. 🎚",
    "Discover one new thing about your partner each day. 🔎",
    "Even in chaos, give them a look that says 'I see you.' 👁",
    "Talk about your boundaries — respect needs clarity. 🚧",
    "Speak about their strengths to your friends too. 🔊",
    "Sandwich a critique with an appreciation. 🥪",
    "When planning, *really* ask for their input. 🗓",
    "Speak about past feelings without judgment — that's honesty. 🪶",
    "Never enter a fight as 'win-lose'. 🤝",
    "Make a shared bucket-list — small and bold items. 📋",
    "Create a shared ritual — like morning coffee. ☕",
    "Sometimes presence is enough — you don't always need a fix. 🌿",
    "Recall a tiny detail from the day you first met. 🌟",
    "If you were wrong, apologize fast — no clauses. 🙇‍♀️",
    "Reserve one hour a week for 'deep talk only'. 🕐",
    "When stuck, change the scenery — go out for dinner. 🍽",
    "If distance creeps in, take the first step yourself. 👣",
    "Pick a small wish they've mentioned and surprise them. 🎁",
    "Find one shared weakness and fight it together. 🥊",
    "Watch their breathing — you'll learn when they're upset. 🌬",
    "Don't suppress bad feelings — voice them gently. 🌧",
    "Praise the ordinary: 'You walked beautifully today.' 💃",
    "If they don't get you, check yourself first: was I clear? 🗣",
    "No relationship grows without feedback. 📈",
    "Make a 'no-expectation' night — just be. 🌌",
    "Always winning is the worst kind of loss in love. 🏳️",
    "When bad news lands, hug first, ask later. 🤗",
    "Support their hobby even if it bores you. 🎨",
    "Set a magic word — when one says it, it means 'I'm tired, be kind.' 🔑",
    "Celebrate one small win every week. 🥂",
    "When you don't understand their sadness, say 'you're allowed to feel this.' 💧",
    "Keep a shared good-vibes journal. 📔",
    "If it goes cold, be the first to break the ice. ❄️➡️💧",
    "A 5-minute foot massage can revive a whole week. 💆",
    "Don't dodge responsibility — responsibility *is* love. 🧱",
    "Say no to one meeting, yes to one romantic dinner. ❤️",
    "Film one funny thing they say — golden memory. 🎥",
    "On hard nights, just write 'I'm here' — that's enough. ✍️",
    "Don't compare your story to anyone else's — each one is its own book. 📕",
    "Archive old grievances — don't bring them to every fight. 📦",
    "Start a 'partner's day' — one day a month all about them. 🎉",
    "If something loops in your head, write a letter — send it or burn it. 📜",
    "With guests, introduce your partner first — make them feel important. 🌟",
    "Ask them something you've never asked before. 🌀",
    "Take a photo of their laugh — it'll save you on dark days. 📸",
    "If your thoughts spiral at night, promise yourself you'll talk in the morning. 🌙",
    "Don't send heavy texts at night — tone changes by morning. 🌅",
    "When they're sick, even a simple tea is a love story. 🍵",
    "Use a shared sweet memory as an anchor when grief comes. ⚓",
    "Give 3 daily hours work-free, together. ⏱",
    "If something bothers you, say it the same day — not a month later. ⚡",
    "Keep a 'box of old texts' — a love archive. 💌",
    "In fights, swap 'you always' for 'I feel'. 🗣",
    "If they go quiet, don't panic — give them space. ☁️",
    "Be afraid of one new thing together (rollercoaster?). It bonds you. 🎢",
    "Make one hearty laugh happen this week. 🤣",
    "When they achieve something, celebrate it *more* than your own. 🥳",
    "When they're sad, bring a warm drink. Words aren't needed. ☕",
    "Before you say it, look at yourself from outside. 🪞",
    "Thank yourself for something you're grateful for in *you*. 🙏",
    "Now and then, swap roles — they plan the day. 👑",
    "When you go silent, just write: 'I don't know what to say, but I'm here.' 🤍",
    "If you want change, start with you. 🌱",
    "Learn to say 'I don't know' with confidence. 🤷",
    "Every fight should leave you one step closer, not further. 🤝",
    "Each night, share one gratitude before sleeping. 🌌",
    "At parties, glance at them often — like the first time. 👀",
    "Tell them about a weakness you've overcome — it inspires. 💪",
    "Daily, share a 10-second silent hug. 🤗",
    "If you must set a boundary, do it kindly — anger doesn't build it. 🚪",
    "Have a movie night with *their* favorite genre — even if you dislike it. 🎬",
    "Use a word you learned from your partner — once a day. 🗝",
    "Don't drag old hurts into every new fight. 🚧",
]


assert len(FA) >= 100, len(FA)
assert len(EN) >= 100, len(EN)
