"""Tiny, doable daily challenges for couples — 80+ in each language."""

FA: list[str] = [
    "امروز قبل از خواب، سه چیز رو که از پارتنرت ممنونی، براش بنویس. 🙏",
    "یه عکس خنده‌دار از یه لحظه‌ی امروز بگیر و بفرستش. 📷",
    "ده دقیقه بدون موبایل، فقط دستِ هم دیگه رو بگیرید. ✋",
    "یه آهنگ از روز اول آشنایی‌تون رو با هم گوش بدید. 🎶",
    "یه کلمه از یه زبان جدید با هم یاد بگیرید. 🌐",
    "خاطره‌ی اولین قرارتون رو با تموم جزئیات تعریف کنید. 📅",
    "امروز فقط با شکلک‌ها به هم پیام بدید. 🤩",
    "یه برنامه‌ی غذایی جدید با هم بپزید. 👨‍🍳",
    "هر کدوم یه نقطه قوت پارتنرتون رو روی کاغذ بنویسید و باهم بخونید. 📝",
    "ده دقیقه به هم خیره بشید بدون حرف زدن. 👀",
    "یه رؤیای بزرگ که داری، براش تعریف کن. 🎯",
    "یه قرار «۵ ساله» بگذارید — کجا می‌خواید باشید؟ 🗓",
    "با هم یه قسمت از کتاب بخونید (صوتی یا متنی). 📚",
    "یه نامه‌ی دستی برای پارتنرت بنویس. ✍️",
    "ده مورد از علاقه‌مندی‌هات رو بنویس و باهاش مقایسه کن. 📑",
    "یه ورزش سبک ۱۵ دقیقه‌ای با هم انجام بدید. 🧘",
    "هر کدوم یه ضعفت رو روی کاغذ بنویس و باهم بسوزونیدش. 🔥",
    "یه قهوه یا چای دو نفره بدون موبایل. ☕",
    "یه فیلم بدون دیالوگ پیدا کنید و باهم تماشا کنید. 🎬",
    "یه رازی که هیچ‌کس نمی‌دونه، با اون شریک شو. 🤫",
    "یه طرح ساده از پارتنرت بکش، حتی اگه نقاش نیستی. 🎨",
    "یه شعار مشترک برای رابطه‌تون بسازید. 🏷",
    "ده ثانیه فقط نفس‌های هم رو حس کنید. 🌬",
    "یه «اگه قرار بود ۳ کشور رو ببینیم» لیست بسازید. ✈️",
    "هر کدوم یه آهنگ پلی‌لیست بسازید، یه آهنگ از همدیگه. 🎵",
    "از یه سفر کوچیک، خاطرات و عکس‌ها رو با هم مرور کنید. 🌄",
    "ده دقیقه «شکر گزاری» کنید — هر کدوم به نوبت. 🙏",
    "از یه ترسی که داری بگو و باهاش روبه‌رو شو. 😱",
    "یه روز کلِ کارها رو با هم انجام بدید — حتی شستن ظرف. 🍽",
    "یه عکس فیلتر‌نخورده‌ی ساده از خودت براش بفرست. 📸",
    "هر کدوم یه آرزو برای ۲۰ سال آینده‌ی هم بنویسید. 📜",
    "یه گیاه با هم بکارید و اسم بگذارید. 🪴",
    "یه چیز جدید رو با هم تجربه کنید — حتی یه طعم غذا. 🍱",
    "ده دقیقه با هم برقصید — بدون قاعده. 💃",
    "هر کدوم یه عکس قدیمی از کودکی پیدا کن و باهم نگاه کنید. 🧸",
    "یه شب بدون چراغ، فقط با شمع. 🕯",
    "از یه ضعف خودت تعریف کن و چطور باهاش راه میای. 🌱",
    "یه چیزی که از هم آموختید بنویسید. 📒",
    "هر کدوم یه «اولین بار»ی رو با هم بسازید (مثلاً اولین خوراکی جدید). 🥡",
    "ده دقیقه قبل خواب فقط هم رو بغل کنید. 🤗",
    "یه پادکست رمانتیک با هم گوش بدید. 🎙",
    "یه «شب کیف کن» — هر کاری که اون می‌گه. 🎫",
    "یه شب کاملاً بی‌برنامه — فقط با هم. 🚪",
    "هر کدوم یه آرزو که سال قبل داشتید، براش گزارش بدید. 📊",
    "ده دقیقه روی شانه‌ی هم سر بگذارید — بدون حرف. 🌙",
    "یه «اسم مخفی» برای همدیگه بسازید. 🦊",
    "از یه پیشرفت پارتنرت تعریف کن و بفرست. 📈",
    "یه چیزی که بهش افتخار می‌کنی روی کاغذ بنویس و بهش بده. 🏆",
    "از خاطره‌های مشترک یه پلی‌لیست بسازید. 📼",
    "یه روز ۲۴ ساعت بدون دعوا — حتی شوخی هم نه. 🕊",
    "هر کدوم یه چیز رو که از خودتون متنفرید بگید — بعد همدیگه رو دلداری بدید. 🌿",
    "یه کلاس آنلاین کوتاه با هم ببینید. 💻",
    "یه شب «بدون دلیل» جشن بگیرید. 🥂",
    "ده دقیقه با هم ساکت بمونید و فقط به صدای محیط گوش بدید. 🌿",
    "از خاطره‌ی بدی که با هم رد کردید، یاد کنید و خنده‌ش کنید. 😅",
    "یه شب فقط با خاطرات قدیمی — هیچ تلفنی هم نه. 📞🚫",
    "از یه «صبر» مشترک تعریف کنید. ⏳",
    "یه «نقشه‌ی گنج» برای آینده‌ی رابطه‌تون بکشید. 🗺",
    "یه شب کاملاً «صادق» — حتی سؤال‌های ترسناک. 🎤",
    "هر کدوم یه «۳ آرزو» برای رابطه‌تون بنویسید. 🌠",
    "یه «شب نوستالژی» — اولین فیلمی که با هم دیدید رو دوباره ببینید. 🎞",
    "یه پیاده‌روی شبانه ۲۰ دقیقه‌ای. 🌌",
    "ده دقیقه با هم خاطره‌ی بد رو روی کاغذ بنویسید و پاره کنید. ✂️",
    "هر کدوم یه «این بهترین چیز» در پارتنرتون رو پیدا کنید. 🌟",
    "یه «ست عکس» قشنگ از یه گردش با هم. 📸",
    "از یه سؤال «اگه دوباره به دنیا بیای» شروع کن. 🌍",
    "یه دستِ ساده با هم بازی کنید — حتی دوز. 🎲",
    "ده دقیقه از روزتون رو با هم برنامه‌ریزی کنید. ⏰",
    "هر کدوم یه کلمه‌ی خاص خودش، روی کاغذ بنویس و توضیح بده. 🔤",
    "یه «شام بدون چاقو و چنگال» — به سبک پیک‌نیک. 🥪",
    "از یه خاطره‌ی شیرین خانوادگی پارتنرت بگو. 👨‍👩‍👧",
    "یه روز «بدون اخبار» — فقط با همدیگه. 📵",
    "یه شب «پشت‌بام» — به آسمون نگاه کنید. ⭐",
    "یه «صدا»ی مشترک پیدا کنید (مثلاً صدای باران). 🌧",
    "هر کدوم یه «بهترین کاری که اون برام کرده» رو بگید. 💖",
    "از یه «نقطه‌ی ضعف» رابطه‌تون با مهربونی حرف بزنید. 🧷",
    "یه «هدیه‌ی ۰ تومنی» بدید — یه چیز که فقط با وقت ساخته بشه. 🎁",
    "از خاطره‌ی شب اول با هم بودن، با جزئیات تعریف کنید. 🌃",
    "هر کدوم یه «من خاطره‌مم» نوشت — یه پاراگراف از خودتون به آینده. 🕰",
    "یه شب «بدون رختخواب» — روی فرش یا کاناپه بخوابید. 🛋",
    "یه «شب کارت‌بازی» با خاطره‌ها. 🃏",
    "هر کدوم یه «رؤیای ترسناک» رو بگید و بخندیدش. 😱",
    "از یه «اتفاق روز» جزئی، یه قصه‌ی قشنگ بسازید. 📖",
]


EN: list[str] = [
    "Tonight, write down three things you're grateful for about your partner. 🙏",
    "Take a goofy photo of something funny today and send it. 📷",
    "Hold hands for ten minutes — phones away. ✋",
    "Listen together to a song from when you first met. 🎶",
    "Learn one word in a new language together. 🌐",
    "Retell your first date — every detail you remember. 📅",
    "Text each other in emojis only, all day. 🤩",
    "Cook one new dish together tonight. 👨‍🍳",
    "Write down one strength of your partner; share aloud. 📝",
    "Stare into each other's eyes silently for ten minutes. 👀",
    "Share a big dream you're chasing. 🎯",
    "Make a 'five-year' wish: where will you be? 🗓",
    "Read a chapter of a book together (aloud or audio). 📚",
    "Hand-write a letter for your partner. ✍️",
    "List ten of your hobbies and compare. 📑",
    "Do a 15-minute light workout together. 🧘",
    "Write one weakness on paper and burn it together. 🔥",
    "Coffee or tea date — no phones. ☕",
    "Watch a movie with no dialogue together. 🎬",
    "Share one secret no one else knows. 🤫",
    "Draw a quick portrait of your partner — even if you can't. 🎨",
    "Make a shared motto for your relationship. 🏷",
    "Feel each other's breath for ten silent seconds. 🌬",
    "Make a 'three countries to visit' list together. ✈️",
    "Each curates a playlist with one song *from* the other. 🎵",
    "Look through photos of a small trip together. 🌄",
    "Take turns saying gratitudes for ten minutes. 🙏",
    "Share one fear and gently face it together. 😱",
    "Do *all* daily chores together for one day. 🍽",
    "Send an unfiltered, simple selfie. 📸",
    "Each writes a wish for the other's next 20 years. 📜",
    "Plant something together and name it. 🪴",
    "Try one brand-new thing together — even a taste. 🍱",
    "Dance for ten minutes — no rules. 💃",
    "Find a childhood photo and share it. 🧸",
    "Lights off, candles on — for one night. 🕯",
    "Share one of your weaknesses and how you cope. 🌱",
    "Write down one thing you learned from each other. 📒",
    "Create a 'first' together (a new snack? a path?). 🥡",
    "Cuddle ten minutes before sleep. 🤗",
    "Listen to a romantic podcast together. 🎙",
    "'Their night' — whatever they choose. 🎫",
    "A totally unplanned evening — just be. 🚪",
    "Each reports on a wish you had last year. 📊",
    "Rest your head on each other's shoulder — silently — for ten minutes. 🌙",
    "Make secret nicknames for each other. 🦊",
    "Praise a recent progress of theirs in writing. 📈",
    "Write something you're proud of them for. 🏆",
    "Make a playlist of shared memories. 📼",
    "One 24-hour day with zero arguments — not even jokes. 🕊",
    "Each says one thing you hate about yourself — comfort the other. 🌿",
    "Watch a short online class together. 💻",
    "Celebrate a 'no-reason' night. 🥂",
    "Sit quietly together for ten minutes — listen to the room. 🌿",
    "Recall a hard memory and find the humor in it. 😅",
    "An old-memories-only night — no phones. 📞🚫",
    "Share a 'patience' you grew through together. ⏳",
    "Draw a 'treasure map' for your relationship's future. 🗺",
    "An honesty night — even the scary questions. 🎤",
    "Each writes 3 wishes for your relationship. 🌠",
    "Nostalgia night — rewatch your first movie together. 🎞",
    "A 20-minute evening walk. 🌌",
    "Write a bad memory together and tear it up. ✂️",
    "Each finds one 'best thing' about the other. 🌟",
    "A photo set from one outing — curated together. 📸",
    "Start with: 'If you were born again…'. 🌍",
    "Play a simple game — tic-tac-toe even. 🎲",
    "Plan one shared block of your day. ⏰",
    "Each shares a word special to them and why. 🔤",
    "A 'no-cutlery dinner' — picnic style. 🥪",
    "Share one sweet family memory of your partner's. 👨‍👩‍👧",
    "A no-news day — just each other. 📵",
    "A rooftop night — gaze at the sky. ⭐",
    "Find a 'shared sound' (rain? river?). 🌧",
    "Each tells one 'best thing they've done for me'. 💖",
    "Gently discuss one weak spot of your relationship. 🧷",
    "Give a 'zero-dollar gift' — time, not money. 🎁",
    "Retell your first night together — in detail. 🌃",
    "Each writes a paragraph from yourself to your future self. 🕰",
    "Sleep tonight on the floor or couch — not the bed. 🛋",
    "A card-game night with memories. 🃏",
    "Each shares a scary dream and laugh about it. 😱",
    "Spin a small daily moment into a beautiful little story. 📖",
]


assert len(FA) >= 80, len(FA)
assert len(EN) >= 80, len(EN)
