"""Ready-to-send compliments — 100+ in each language.

These are phrased so you (or the bot) can address them directly to a
partner; use the ``{partner}`` placeholder in the template above where
the bot wraps them.
"""

FA: list[str] = [
    "صدای خنده‌ت قشنگ‌ترین آهنگ این هفته‌ست.",
    "وقتی فکر می‌کنی، چشمات یه حالت خاصی پیدا می‌کنه که عاشقشم.",
    "بودنت خونه رو واقعاً «خونه» می‌کنه.",
    "تو از همه‌ی فهرست‌های مورد علاقه‌ام، اولشی.",
    "حتی توی خستگی هم، یه آرامش خاصی داری.",
    "بلدی توی شلوغ‌ترین روزها، آرومم کنی.",
    "وقتی حرف می‌زنی، انگار همه‌ی دنیا یه لحظه می‌ایسته.",
    "هیچ کس مثل تو نمی‌فهمم چی می‌خوام.",
    "تو بهترین تصمیم زندگیمی، بدون حتی یک «اما».",
    "نگاه‌هات معنی‌های هزار کلمه دارن.",
    "یه‌جوری دلگرمم می‌کنی که هیچ کس بلد نیست.",
    "صبر و مهربونیت، الگو‌ست برام.",
    "تو همون آدم خاصی هستی که توی هر فیلم آرزو می‌کردم.",
    "وقتی کنارمی، حتی غذای ساده هم لوکس می‌شه.",
    "یه چیز خاص تو وجودت هست که دلِ آدمو گرم می‌کنه.",
    "هر روز که می‌گذره، بیشتر بهت می‌بالم.",
    "حتی توی سکوت هم، بلدی همه چی رو واضح کنی.",
    "تو یه ترکیب کمیابی از قدرت و مهربونی.",
    "هر کاری می‌کنی، یه‌جور ظرافت داره.",
    "وقتی توی فکری، خیلی جذابی.",
    "حضورت بهترین درمان روزای سختمه.",
    "یه چیزی توی نگاهت هست که هیچ‌وقت نمی‌فهمم چیه — ولی عاشقشم.",
    "تو شجاع‌ترین آدمی هستی که می‌شناسم.",
    "مهربونی‌ت رو حتی به آدمای غریبه می‌بخشی.",
    "بزرگ‌ترین برد زندگیم، وقتی بود که تو رو پیدا کردم.",
    "می‌تونی با یه «حالت چطوره؟» همه‌ی روزم رو نجات بدی.",
    "وقتی می‌خندی، انگار همه‌ی دنیا یه‌بار دیگه شارژ می‌شه.",
    "تو مدل خاصِ خودتی — و این تمومه قشنگیته.",
    "شجاعت داری حتی توی ضعف‌هات.",
    "یه‌جوری بغلم می‌کنی که انگار هیچ‌چیز توی دنیا اشتباه نیست.",
    "هیچ‌کس مثل تو بلد نیست «خوب» باشه.",
    "وقتی هستی، حتی خاکستری‌ها رنگ می‌گیرن.",
    "خواندنت مثل خوندن یه کتاب کلاسیکه — هر بار یه چیز جدید.",
    "اخلاقت، نه فقط جذابیتت، عاشقم می‌کنه.",
    "یه‌جوری کنارم می‌ایستی که حس می‌کنم هیچ‌چیز نشدنی نیست.",
    "وقتی به چیزی اعتقاد داری، انرژی‌ت قابل توقف نیست.",
    "صداقتت یه گنج کمیابه.",
    "حتی وقتی خسته‌ای، یه نور خاصی توی چهره‌ته.",
    "بلدی شنونده‌ی واقعی باشی — مهارتیه که خیلی‌ها ندارن.",
    "تو نه چیزی که داری، یه چیزی که هستی، فوق‌العاده‌ست.",
    "هر تصمیمی که می‌گیری، یه کلاس درس برام داره.",
    "توی هیچ شخصیت‌بازی‌ای، خوب نیستی — این بهترین چیزته.",
    "حضورت یه جور «امنیت روانی» می‌سازه.",
    "هیچ‌چیز توی این دنیا، به اندازه‌ی توجهت لاکچری نیست.",
    "اشتیاقت تو یاد گرفتن، الهام‌بخشه.",
    "می‌تونی توی هر شرایطی، یه شوخی پیدا کنی.",
    "تو همون چیزی هستی که یه «روز سخت» رو می‌سازی روز خوب.",
    "صورتت رو هزار بار ببینم، باز قشنگه.",
    "وقتی می‌گی «نمی‌دونم»، حسش با شجاعته.",
    "ذره‌بینی برای دیدن قشنگی‌های کوچیکه دنیا، فقط تو داری.",
    "وفاداری‌ت بزرگ‌ترین هدیه‌ی زندگیمه.",
    "می‌دونی چطور یه ساعت معمولی رو خاص کنی.",
    "حواست به جزئیات هست — ولی توی آدما، نه فقط چیزها.",
    "هر آدمی توی زندگیت رو، یه‌جوری بهتر می‌کنی.",
    "وقتی توی آشپزخونه‌ای، انگار جشن گرفته شده.",
    "وقت گذاشتن باهات، گرون‌ترین چیزه — ولی هیچ‌وقت پشیمون نیستم.",
    "بلدی «نه» بگی و این جذابه.",
    "یه‌جوری گریه می‌کنی که آدم می‌خواد محافظت کنه.",
    "ذهنت یه باغ پر گله، که هر روز دارم بیشتر کشفش می‌کنم.",
    "حتی توی اشتباه‌هات، یه صداقت داری.",
    "کنار تو بودن، یه مدیتیشن دائمیه.",
    "صدای دست‌خط‌ت توی سرم می‌چرخه — حتی بدون اینکه چیزی بنویسی.",
    "از هر شکستی، یه درس بیرون می‌کشی — و این فوق‌العاده‌ست.",
    "هر بار که می‌بینمت، یه چیز جدید عاشقش می‌شم.",
    "تو بلدی توی یه دنیای پر سر و صدا، آروم بمونی.",
    "ذوقت تو کارهای کوچیک، دل آدم رو می‌بره.",
    "حتی اشتباه‌های گذشته‌ت رو، شرافتمندانه پذیرفتی.",
    "نگاهت تنها چیزیه که می‌تونه قلبم رو هم آروم کنه هم تند کنه.",
    "بلدی توی یه ثانیه از یه آدم سرد، یه آدم گرم بسازی.",
    "حتی توی بدترین روزات، یه ‌جوری شجاع و مهربونی.",
    "هر چقدر روی خودت کار می‌کنی، فقط جذاب‌تر می‌شی.",
    "تو نه فقط دوست‌دختر/دوست‌پسر، که یه «یاور» واقعی هستی.",
    "بلدی توی شلوغ‌ترین جا، فقط برای من باشی.",
    "می‌تونی توی یه نگاه، بفهمی چی توی دلم می‌گذره.",
    "هیچ کس مثل تو نمی‌تونه با یه جمله، روزم رو نجات بده.",
    "حضورت یه یادآوریه که آدم‌های قشنگ هنوز هستن.",
    "هر چی می‌گذره، ارزش‌مندتر می‌شی.",
    "بلدی هم بخندونی، هم آروم کنی، هم تکونم بدی.",
    "اخلاق کاری‌ت یه نمونه‌ی واقعیه.",
    "حتی توی استرس، یه شوخی پیدا می‌کنی.",
    "تو همون «خانوم/آقای ایده‌آلی» هستی که فکر می‌کردم وجود نداره.",
    "صدای راه رفتنت تو راهرو، خوش‌رنگ‌ترین صدای دنیاست.",
    "تو نه «خوبی»، تو «خاصی» — و بین این دو فاصله‌ای هست.",
    "حتی غمت رو هم با وقار حمل می‌کنی.",
    "هر روز یه کلمه‌ی جدید برای توصیفت پیدا می‌کنم.",
    "وقتی به چیزی می‌رسی، انرژی‌ت کلِ اتاق رو پر می‌کنه.",
    "تو یه دلیل قانع‌کننده‌ای برای امیدوار موندن به آدما.",
    "صبوری‌ت با خانواده‌ت، عاشقم می‌کنه.",
    "حتی وقتی خشمگینی، هنوز بلدی منطقی باشی.",
    "هر بار با تو راه می‌رم، حس می‌کنم سرعت قلبم تنظیم شده.",
    "حواست به سلامتیت هست — این برام جذاب‌ترین چیزه.",
    "ذهنت یه ابزار قشنگه — و قلبت یه گنج.",
    "هر کسی توی زندگیت، شانس میاره.",
    "می‌دونی چطور توی هر شرایطی، انتخابِ درست رو ببینی.",
    "حتی توی سفر، خونه‌مون با توئه.",
    "صدای زنگ خنده‌ت رو، با هیچ آهنگی عوض نمی‌کنم.",
    "تو یه دلیل واقعی برای «خدا رو شکر» گفتن منی.",
    "بلدی توی ضعفت قوی باشی، و توی قدرتت متواضع.",
    "هرگز ادای کسی رو در نمیاری — این جذاب‌ترین چیزته.",
    "تو از همه‌ی کلیشه‌ها فراری — و این بهترین ویژگیته.",
    "می‌تونی یه روز معمولی رو با یه پیام، خاص کنی.",
    "حتی خشمت هم زبون مهربون داره.",
    "ذکاوتت زیر یه قلب گرم پنهانه — این بهترین ترکیب دنیاست.",
    "همیشه «خود واقعی» هستی — و این یه هنر بزرگه.",
    "هر کاری می‌کنی، تموم وجودت رو می‌بری توش.",
]


EN: list[str] = [
    "Your laugh is the prettiest melody of my week.",
    "Your eyes do this thing when you're thinking — and I love it.",
    "Your presence turns a house into a home.",
    "You top every favorites list I've ever made.",
    "Even tired, you carry a peace I rarely see.",
    "You can calm me on my loudest days.",
    "When you speak, the world quietly waits.",
    "No one reads me like you do.",
    "You're the best decision I've ever made — no 'but'.",
    "Your glance carries a thousand words.",
    "You reassure me like no one else can.",
    "Your patience and kindness are my model.",
    "You're the rare character I used to wish movies were real for.",
    "Even simple food feels fancy when you're near.",
    "There's something in you that warms a heart.",
    "Each day I'm prouder of you.",
    "Even in silence, you make things clear.",
    "You're a rare blend of strength and gentleness.",
    "Everything you do has a quiet elegance.",
    "You look beautiful when you're lost in thought.",
    "Your presence heals my hardest days.",
    "There's something in your gaze I'll never decode — and I adore it.",
    "You're the bravest person I know.",
    "You're kind even to strangers.",
    "My greatest win in life is finding you.",
    "Your simple 'how are you?' can save my whole day.",
    "When you smile, the world recharges.",
    "You are your own kind — and that's your beauty.",
    "You bring courage to your weaknesses.",
    "Your hugs feel like nothing is wrong in the world.",
    "No one is 'good' the way you are.",
    "When you're near, even gray things gain color.",
    "Reading you is like reading a classic — always something new.",
    "I love you for your character, not just your charm.",
    "Standing beside you, anything feels possible.",
    "When you believe in something, your energy is unstoppable.",
    "Your honesty is a rare treasure.",
    "Even tired, your face carries a soft light.",
    "You're a true listener — a skill few have.",
    "Not what you have, but what you *are* is extraordinary.",
    "Every choice you make is a tiny lesson for me.",
    "You're terrible at pretending — and it's perfect.",
    "Your presence creates emotional safety.",
    "Nothing in this world is as luxurious as your attention.",
    "Your eagerness to learn is inspiring.",
    "You can find a joke in any situation.",
    "You're the reason a hard day turns good.",
    "Your face is beautiful the thousandth time too.",
    "Your 'I don't know' has the bravery of a thousand words.",
    "You have a unique lens for life's tiny beauty.",
    "Your loyalty is the biggest gift of my life.",
    "You can make an ordinary hour feel special.",
    "You notice details — in people, not just things.",
    "You make everyone in your life a little better.",
    "Your kitchen feels like a celebration.",
    "Time with you is expensive — and I never regret it.",
    "You know how to say no — and it's attractive.",
    "Your tears make me want to protect you.",
    "Your mind is a garden of flowers I keep discovering.",
    "Even in your mistakes, you carry honesty.",
    "Being beside you is a quiet meditation.",
    "Your handwriting sound rings in my head — without you writing.",
    "You extract a lesson from every loss.",
    "Every time I see you, I love a new thing about you.",
    "You can stay calm in a loud world.",
    "Your joy in tiny tasks steals hearts.",
    "You own your past mistakes with grace.",
    "Your gaze can both calm and quicken my heart.",
    "You can turn a cold person warm in one second.",
    "Even on your worst day, you're brave and kind.",
    "The more you work on yourself, the more attractive you grow.",
    "You're not just my partner — you're a real teammate.",
    "You can be only with me in the busiest place.",
    "You read my heart in one glance.",
    "No one saves my day with one sentence like you.",
    "You're proof beautiful people still exist.",
    "You only become more precious with time.",
    "You make me laugh, calm me, and shake me — all in one.",
    "Your work ethic is the real deal.",
    "Even under stress, you find humor.",
    "You're the ideal I thought wasn't real.",
    "The sound of your footsteps in the hall is the prettiest in the world.",
    "You're not 'nice' — you're 'special'. There's a difference.",
    "You carry your sadness with grace too.",
    "I find a new word to describe you every day.",
    "When you succeed, your energy fills the room.",
    "You're a real reason to stay hopeful about people.",
    "Your patience with your family makes me love you more.",
    "Even when angry, you stay reasonable.",
    "Walking with you regulates my heartbeat.",
    "You take care of your health — irresistibly attractive.",
    "Your mind is a beautiful tool — your heart, a treasure.",
    "Everyone in your life is lucky.",
    "You know the right choice in any situation.",
    "Even in travel, home is wherever you are.",
    "I wouldn't trade the sound of your laugh for any song.",
    "You're a real reason for my 'thank God'.",
    "You're strong in weakness, humble in strength.",
    "You never imitate — and that's your most attractive thing.",
    "You escape clichés — your best trait.",
    "You can make an ordinary day special with one text.",
    "Even your anger speaks gently.",
    "Your wit hides beneath a warm heart — the best mix in the world.",
    "You always show up as your real self — a big art.",
    "Whatever you do, you put your whole self into it.",
]


assert len(FA) >= 100, len(FA)
assert len(EN) >= 100, len(EN)
