"""Love quote catalog — 200+ unique items in Persian and English.

Use ``content.get_catalog('quotes', lang)`` to access them. Each item's
position in the list is its stable ID used by the no-repeat tracker.
"""

# ---------------------------------------------------------------- Persian (FA)
FA: list[str] = [
    "عشق یعنی پیدا کردن خونه‌ای که هیچ‌وقت لازم نیست ترکش کنی. 💕",
    "بهترین داستان‌های عاشقانه اون‌هایی‌اند که هنوز در حال نوشته شدن‌اند. 📖",
    "تو همون آدمی هستی که شعرهای دنیا داره راجع‌بهش حرف می‌زنه. 🌹",
    "عشق واقعی صدای دو قلبه که با یه ریتم می‌تپن. 💓",
    "هر روز با تو، روز شنبه‌ی قلبمه. 🌞",
    "وقتی کنارتم، حتی سکوت هم آهنگ می‌شه. 🎶",
    "تو نه عادت من، که اصل من شدی. 🌟",
    "عشق یعنی همیشه برگردی به همون آغوش، حتی وقتی همه چی تغییر کرده. 🤗",
    "تو دلیلی هستی که هنوز به آدم‌ها امیدوارم. 💖",
    "بزرگ‌ترین معجزه‌ی زندگی من، تلاقی نگاهمون توی یه روز معمولی بود. ✨",
    "عشق چیزی نیست که پیدا می‌کنی؛ کسی‌ست که حاضره با تو ساخته بشه. 🛠💞",
    "هر کلمه‌ای که با تو می‌گم، قشنگ‌تر از دفعه قبل می‌شه. 🗣️",
    "تو هوای بعد از باران زندگیم هستی. 🌧️🌈",
    "بعضی آدم‌ها رو خدا روی روح آدم تتو می‌کنه؛ تو یکی از اون‌هایی. 🖋",
    "اگر تو نباشی، دلیلی برای اینکه «صبح» باشه باقی نمی‌مونه. 🌅",
    "تو همون چیزی هستی که فکر می‌کردم فقط تو فیلم‌ها وجود داره. 🎬",
    "عشق یعنی کسی که حتی توی روزای بد، تو رو انتخاب می‌کنه. 🌧️💪",
    "قلبم رو دارم می‌گم بهت؛ مراقبش باش، چون فقط همینه. ❤️",
    "تو لبخند منی، حتی وقتی توی شهر تو نیستی. 😊",
    "هیچ تعطیلی‌ای به اندازه‌ی یه شب با تو، آرامش نداره. 🌙",
    "وقتی دستت رو می‌گیرم، انگار همه‌ی دنیا برام مهربون می‌شه. 🤲",
    "تو کلمه‌ای هستی که زبون‌ها نمی‌تونن کاملش بگن. 🤐💞",
    "بزرگ‌ترین جنگ‌های زندگیم رو با عشق تو بُردم. 🛡️",
    "هر بار که می‌خوام تو رو توضیح بدم، شعر می‌شم. 📜",
    "تو همون آدمی هستی که خدا قبل از خواب براش دعا می‌کرد. 🙏",
    "عشق یعنی دو نفر، یه ایده، یه آینده. 🌱",
    "بعضی‌ها تو خاطرت می‌مونن، بعضی‌ها تو نفس‌هات. تو تو نفس‌هامی. 🌬️",
    "تو نه شبیه هیچ‌کسی، نه می‌ذاری دلتنگ هیچ‌کس باشم. 💗",
    "عشق یعنی وقتی هیچ‌کس نیست، تو هستی. وقتی هستی، انگار همه‌ی دنیا اونجاست. 🌍",
    "تو رو پیدا کردم؛ بقیه‌ی زندگی فقط داره خودش رو معنی می‌کنه. 🧩",
    "هر روز با تو، یه فصل تازه از کتاب من شروع می‌شه. 📚",
    "عشق یعنی مجبور نباشی نقش بازی کنی. 🎭❌",
    "وقتی می‌خندی، انگار دنیا برام پنج درجه گرم‌تر می‌شه. ☀️",
    "تو همون شعری هستی که قبل از به دنیا اومدنم تو دلم بود. 📝",
    "می‌گن «خانه جایی‌ست که قلبت آنجاست» — قلب من تو‌یی. 🏠",
    "تو نه یه «انتخاب»، که یه «اتفاق ضروری» تو زندگیم بودی. ⚡",
    "هر چی بزرگ‌تر می‌شم، می‌فهمم تو همون بهترین اتفاق ساده‌ای بودی که زندگی بهم داد. 🌷",
    "عشق یعنی صبح که چشمت رو باز می‌کنی و حس می‌کنی برنده شدی. 🏆",
    "تو رو دوست داشتن، گاهی شبیه نفس کشیدنه — بدون فکر، اما حیاتی. 💨💖",
    "ما با هم یه زبان مخفی داریم که هیچ کلمه‌ای ندارد. 🤫",
    "وقتی تو هستی، حتی ساعت‌های منتظر موندن هم شیرین‌اند. ⏳",
    "تو همون آدمی هستی که نمی‌خوام «عادی» بشه. 🌟",
    "بهترین آدرسی که می‌تونم بدم به دل خودم، اسم توئه. 📍",
    "عشق یعنی «بمون» — حتی وقتی هیچ دلیلی برای موندن نباشه، تو هستی. 🌹",
    "تو همون چیزی هستی که بقیه‌ی دنیا نمی‌تونه کپی‌اش کنه. 🪞",
    "اگه قراره فقط یه جمله بگم، اینه: «خوشحالم که تو هستی». 💞",
    "تو جای خالی‌ای که نمی‌دونستم تو قلبم وجود داره رو پُر کردی. 🧡",
    "هر روز بهت می‌گم دوستت دارم — چون هر روز عاشق‌تر می‌شم. 🔁",
    "می‌خوام تا آخرش با تو باشم، حتی وقتی «آخر» معنی نداشته باشه. ♾️",
    "تو یعنی خونه، یعنی پناه، یعنی همه‌ی جاهایی که قلب آدم آرومه. 🏡",
    "عشق یعنی توی شلوغی، یه نفر رو با چشم بسته پیدا کنی. 👁️‍🗨️",
    "تو همون آرامشی هستی که من سال‌ها دنبالش بودم. 🕊️",
    "هر چقدر فاصله بینمون باشه، قلبم بلده خودش رو بهت برسونه. 💌",
    "تو بهترین چیزی هستی که از همه‌ی شکست‌هام به دست آوردم. 🌻",
    "وقتی تو هستی، حتی روزای خاکستری رنگ می‌گیرن. 🎨",
    "ما کنار هم تموم نمی‌شیم — فقط شکل‌های جدیدی از عشق رو کشف می‌کنیم. 🔄",
    "تو همون نسخه‌ای از زندگی هستی که هیچ‌وقت نمی‌خوام پاکش کنم. 💾",
    "هر کاری می‌کنی، عشق رو یه پله بالاتر می‌بری. 🪜",
    "تو همون لبخند ساعت ۲ بامدادی هستی که هیچ‌کس نمی‌بینه، ولی همه چی رو نگه می‌داره. 🌙",
    "بهترین حس دنیا، حس امنیتیه که توی آغوش تو دارم. 🛡️",
    "عشق یعنی هیچ‌وقت تنها نیست‌ای، حتی وقتی تنهایی. 👫",
    "تو نه «نیمه‌ی گمشده»، که اون قسمتی هستی که من اصلاً نمی‌دونستم گمش کردم. 🧭",
    "اگه دنیا فردا تموم بشه، آخرین کاری که می‌کنم بغل کردن توئه. 🤗",
    "وقتی صدای نفس‌هات رو می‌شنوم، دنیا یه‌خرده با عقل‌تر می‌شه. 🫁",
    "عشق یعنی هیچ روزی شبیه قبلی نمی‌شه. 🌅🌄",
    "تو همون خاطره‌ای هستی که نمی‌ذارم تموم بشه. 📷",
    "هر چی توی زندگیم اتفاق بیفته، خدا رو بخاطر تو شکر می‌کنم. 🙏",
    "تو رو که دارم، انگار همه‌ی فصول سال بهارن. 🌸",
    "صبح‌ها چشم‌هام رو فقط برای دیدن تو باز می‌کنم. 👀",
    "عشق ما اون چیزی نیست که به دنیا نشون می‌دیم؛ اون چیزی‌ست که فقط مال خودمونه. 🔐",
    "تو همون آدمی هستی که حتی دعواهامون هم پر از مهربونی‌اند. 💕",
    "بعضی شب‌ها فقط با فکر کردن به تو می‌خوابم. ✨",
    "تو همون «دلیلِ امروزِ من» هستی. 🌟",
    "عشق یعنی وقتی هیچ‌کس باور نداره، تو دستم رو می‌گیری. 🫂",
    "هر نفسی که می‌کشم، یه قدم نزدیک‌ترم به تو. 💨💞",
    "تو همون اتفاقی هستی که آرزو می‌کردم تو سن‌های قبلی منتظرم بمونی. 🕯",
    "عشق ما مثل یه نامه‌ست که هیچ‌وقت پاکش نمی‌کنم. 💌",
    "از وقتی تو رو دارم، حتی خستگی‌هام مزه‌ی شیرینی دارن. 🍯",
    "تو همون آدمی هستی که بدون نیاز به حرف، می‌فهمی. 🤫💕",
    "هیچ کلمه‌ای به اندازه‌ی نگاه تو، دل آدم رو گرم نمی‌کنه. 🔥",
    "ما با هم نه دو تا، که یه شخص هستیم با دو تا قلب. 💞",
    "وقتی عاشق توام، یعنی هر کاری برای حفظ این عشق می‌کنم. 🛡️❤️",
    "عشق یعنی توی ضعف‌هات هم تو رو می‌بینم و عاشق‌تر می‌شم. 💖",
    "تو همون قسمتی از من هستی که قبل از تو نمی‌شناختمش. 🪞",
    "هر بار که می‌بینمت، دلم انگار تازه عاشق می‌شه. 💘",
    "می‌خوام تو رو با تموم نسخه‌های آینده‌ت دوست داشته باشم. 📅",
    "تو همون شعر گم‌شده‌ای هستی که من از کودکی دنبالش بودم. 📜",
    "عشق یعنی بدون «اگر» و «اما»، فقط «تو». ❤️",
    "هر روز اولین بار نیست که عاشقت می‌شم — هر روز عاشق‌تر می‌شم. 🔄",
    "تو رو دارم؛ یعنی همه چی دارم. 🌍",
    "آغوش تو، تنها جایی‌ست که جنگ‌های دنیا تمومه. 🕊️",
    "وقتی به تو فکر می‌کنم، تموم دنیام رنگی می‌شه. 🌈",
    "عشق یعنی همه‌ی سوال‌های زندگیم یه جواب داره: تو. 🙌",
    "تو همون چیزی هستی که من بی‌نهایت بار انتخاب می‌کنم. ♾️",
    "هیچ خداحافظی‌ای با تو، آخرین خداحافظی نیست. 👋💕",
    "تو از همه‌ی شب‌بیداری‌هام معذرت می‌خوای، در حالی که خود تو ماه شب‌هامی. 🌜",
    "عشق ما مثل یه آهنگ کلاسیکه — هرچقدر گوش بدی، عمیق‌تر می‌شه. 🎼",
    "تو لازم نیست خاص باشی — تو خود خاصیتی. 💎",
    "می‌گن «هر کس یه نیمه داره» — تو نه نیمه‌ی منی، تو کامل‌کننده‌ی منی. 🧩",
    "بزرگ‌ترین خوشبختی من، عادی‌ترین لحظه‌های با تو بودنه. ☕",
    "تو همون داستانی هستی که می‌خوام تا آخرش بمونم. 📖",
    "هیچ صدایی به اندازه‌ی «دوستت دارم» تو، دل من رو نمی‌لرزونه. 🎙",
    "تو یعنی همه‌ی روزای خوب آینده‌ام. 🌤️",
    "عشق ما یه راز قشنگ بین خودمون و خداست. 🤲",
    "حتی ساده‌ترین صبح‌ها هم با تو، شبیه معجزه‌ست. ☕",
    "تو همون آدمی هستی که قلبم بدون اجازه‌ی من، عاشقش شد. 💓",
    "اگه عشق رنگ داشت، رنگ چشم‌های تو بود. 👁",
    "تو سرود قلبمی، آهنگی که هیچ‌وقت تموم نمی‌شه. 🎵",
    "همه‌ی ساعت‌هام رو با تو میزون کردم. ⏰",
    "نمی‌دونم چطور قبل از تو زندگی می‌کردم؛ شاید زندگی نمی‌کردم، فقط زنده بودم. 🌱",
    "تو همون بهانه‌ای هستی که هر صبح برای بیدار شدن دارم. 🌅",
    "عشق ما رو هیچ ساعت و تقویمی نمی‌تونه اندازه بگیره. ⌛",
    "تو همون جواب همه‌ی دعاهامی. 🤲",
    "وقتی کنارمی، حتی سکوت هم مدل خاصی پر می‌شه. 🤫",
    "تو یعنی قلب من یه آدرس دائمی داره. 🏠",
    "عشق یعنی توی بیداری هم خواب می‌بینی. 💭",
    "هیچ کتابی به اندازه‌ی چشم‌های تو، خوندنی نیست. 📚",
    "تو همون کاری هستی که با تموم وجود انجامش می‌دم. 💪",
    "عشق ما، آرومه — مثل دریا قبل از طلوع. 🌊",
    "تو همون آدمی هستی که با تو، حتی شکست هم زیباست. 🏵",
    "هر روز تو رو پیدا کردن، یه شانس مجدد به زندگیه. 🍀",
    "تو همون پایان خوش داستانم هستی. 🎬",
    "عشق یعنی توی بدترین روزها، تو می‌خندونی‌ام. 😂",
    "ما با هم یه دنیای کوچیک ساختیم که هیچ‌کس وارد نمی‌شه. 🔐",
    "تو همون چیزی هستی که نمی‌خوام عادتم بشه — می‌خوام همیشه تازه بمونی. 🌷",
    "عشق یعنی هر روز یه دلیل تازه برای موندن. 📌",
    "اگه قلبم می‌تونست حرف بزنه، فقط اسم تو رو می‌گفت. 💗",
    "تو همون چیزی هستی که با تموم وجودم می‌خوام محافظت کنم. 🛡",
    "هر بار که بهت فکر می‌کنم، یه‌جای دلم گرم می‌شه. 🔥",
    "تو دلیل لبخندای بی‌دلیل من هستی. 😊",
    "اگه قراره دنیا تموم بشه، می‌خوام آخرین چیزی که می‌بینم چشمای تو باشه. 👁",
    "عشق یعنی دو نفر که با هم سکوت رو هم لذت‌بخش می‌کنن. 🤍",
    "تو همون شعری هستی که قبل از خواب می‌خونمش. 📖",
    "آغوش تو، تنها جای امن این دنیای ناامنه. 🤗",
    "تو همون خواب قشنگیه که نمی‌خوام بیدار بشم. 💤",
    "بدون تو، هیچ کلمه‌ای کامل نیست — حتی «من». 🔤",
    "ما با هم یه آهنگیم که آدما براش می‌رقصن. 🎵",
    "تو همون «هر روز» منی — تکراری و عزیز. 🌞",
    "عشق یعنی به جای دنبال خوشبختی گشتن، خوشبختی رو خلق کنی. ✨",
    "تو یعنی نگاهم به دنیا رنگین شد. 🎨",
    "بدون تو، آینده فقط یه تاریخه؛ با تو، یه قصه‌ست. 📅",
    "تو همون خط آخر داستانی هستی که می‌خوام تموم نشه. ✍️",
    "هر بار دستت رو می‌گیرم، حس می‌کنم همه چی سر جای خودشه. 🤝",
    "عشق ما، اون آرامشیه که توی هیچ کتابی پیدا نمی‌شه. 📕",
    "تو همون آدمی هستی که خدا ازم پنهون نگه داشت تا قدرت رو بدونم. 🙏",
    "هر روز با تو، یه قدمه به سمت بهترین نسخه‌ی خودم. 🚶‍♀️",
    "تو بهترین سؤالی هستی که توی دلم می‌چرخه. 🌀",
    "اگه دنیا یه پازل باشه، تو همون قطعه‌ای هستی که آخرش جای خودش رو پیدا کرد. 🧩",
    "وقتی تو می‌خندی، صدای قلبم بلندتر می‌شه. 💓",
    "تو همون آدمی هستی که با تو، حتی غم هم قابل تحمله. 🌧",
    "هیچ سفری به اندازه‌ی سفر به دل تو، جذاب نیست. 🧳",
    "ما با هم یه زبان بدون کلمه داریم. 🤐💞",
    "عشق یعنی هر روز یاد گرفتن از همدیگه. 📚",
    "تو همون چیزی هستی که توی هیچ آرزویی نمی‌گنجی. 🌠",
    "اگه عاشق بودن جرم باشه، من بزرگ‌ترین مجرم دنیام. 🚔💖",
    "هر چی به تو فکر می‌کنم، دلم بیشتر گرم می‌شه. 🔥",
    "تو یعنی نمی‌ترسم از فردا، چون هر فردا با تو، یه هدیه‌ست. 🎁",
    "عشق ما یه چیزیه که حتی زمان نمی‌تونه بپوسوندش. ⏳",
    "تو همون شعری هستی که نمی‌خوام به کسی نشون بدم. 📜",
    "هر بار بهم لبخند می‌زنی، یه گل توی قلبم باز می‌شه. 🌹",
    "تو همون آدمی هستی که با تو، هیچ روزی تکراری نیست. 🌈",
    "عشق یعنی هیچ سکوتی بین ما، خالی نیست. 🤍",
    "تو همون «شاید»ی هستی که به «حتماً» تبدیل شد. ✅",
    "هر دفعه که اسمت رو می‌گم، انگار دارم یه دعا می‌خونم. 🤲",
    "تو همون قسمتی از زندگیم هستی که نمی‌خوام بازنویسی بشه. ✍️",
    "آغوش تو، تنها جاییه که قلبم احساس راحتی می‌کنه. 🏡",
    "بدون تو، حتی بهار هم رنگش پاییزه. 🍂",
    "تو همون پاسخی هستی که خدا قبل از سؤال من، آماده کرده بود. 🙏",
    "عشق یعنی بدون تو هیچ روزی کامل نیست. 🌗",
    "تو یعنی یه دنیای کوچیک تو دل دنیای بزرگ. 🌍",
    "هر بار که می‌بینمت، انگار اولین بار می‌بینمت. 👀",
    "تو همون آدمی هستی که دلم رو بهش سپردم بدون اینکه بدونم چرا. 💝",
    "عشق ما رو هیچ‌کس نمی‌فهمه — و این قشنگ‌ترین قسمتشه. 🤫",
    "تو همون خوشبختی‌ای هستی که از همه‌ی صبرهام به دست آوردم. ⏳💕",
    "هیچ شب‌بیداری‌ای با فکر تو، خسته‌کننده نیست. 🌙",
    "تو همون آدمی هستی که قلبم بدون پرسیدن، بهش «بله» گفت. ✅",
    "عشق یعنی توی بدترین روزات، تو زیباترین چیزی. 🌷",
    "تو یعنی همه‌ی فردای‌های من، یه دلیل برای امید دارن. 🌟",
    "هیچ نقاشی‌ای به اندازه‌ی چهره‌ی تو، رنگ‌آمیزی‌نشده زیبا نیست. 🎨",
    "تو همون آدمی هستی که هیچ تعریفی، حقش رو ادا نمی‌کنه. 📖",
    "عشق ما اون قسمت ساکت دنیاست که فقط خودمون می‌شنویم. 🤫💕",
    "تو همون چیزی هستی که هزار بار از خدا خواستم. 🤲",
    "هر دفعه که بغلم می‌کنی، یه قسمت از دلتنگی‌هام آب می‌شه. 🤗",
    "تو همون شعری هستی که قلبم می‌نویسه‌ش، بدون اینکه قلم داشته باشه. 🖋",
    "عشق ما رنگی نداره — همه‌ی رنگ‌ها رو با خودش داره. 🌈",
    "تو یعنی هر بار که دلتنگم، یه نقشه‌ی برگشت دارم. 🗺",
    "هر کاری می‌کنم، تو همراهمی — حتی وقتی نیستی. 👤",
    "تو همون مزه‌ی شیرینی هستی که با هیچ شیرینی‌ای مقایسه نمی‌شه. 🍯",
    "آرامش یعنی روی شانه‌ی تو سر گذاشتن. 😌",
    "عشق یعنی توی هر مرحله‌ای از زندگیم، تو حضور داری. 📊",
    "تو همون آدمی هستی که زندگی رو معنی‌دار کرد. 📌",
    "هیچ پایانی برای ما نیست — فقط شروع‌های تازه. 🔁",
    "تو همون چیزی هستی که هیچ‌وقت بهش عادت نمی‌کنم — همیشه تازه‌ای. 🌷",
    "عشق ما مثل یه کتاب کلاسیکه — هر بار خوندنش، یه چیز جدید کشف می‌کنی. 📚",
    "تو یعنی همه‌ی روزای خوب من، یه روز با تو‌اند. 🌞",
    "هر بار که دستات تو دستامه، حس می‌کنم همه‌ی دنیا تو دست منه. 🌍",
    "تو همون آدمی هستی که توی شلوغی، قلبم رو پیدا کرد. 💗",
    "عشق یعنی توی سکوت هم بهش گوش می‌دی. 🎧",
    "تو همون چیزی هستی که هیچ‌وقت تنوع نمی‌خوام. 💫",
    "هر روز یه «دوستت دارم» جدید کشف می‌کنم. 📝",
    "تو همون آدمی هستی که بدون اینکه بخواد، روح من رو لمس کرد. ✨",
    "عشق ما، اون قسمتی از داستانم هست که بعدش هیچی نمی‌تونه پاکش کنه. 🖋",
    "تو همون چیزی هستی که با تو، حتی منتظر موندن هم لذت‌بخشه. ⏳",
    "بدون تو، روزهام سفیدن — تو رنگ زندگیمی. 🎨",
    "تو یعنی هر بار که بهت فکر می‌کنم، دنیا یه‌خرده مهربون‌تر می‌شه. 🌍💞",
    "عشق ما اون چیزیه که هیچ کلمه‌ای نمی‌تونه توصیفش کنه — فقط حسش می‌کنیم. 💕",
    "تو همون جواب همه‌ی «چرا»های زندگیم هستی. ❓",
    "هر صبح، اولین فکر من اسم توئه. 🌅",
    "تو یعنی حتی توی تاریک‌ترین شب‌ها، یه ستاره دارم. ⭐",
    "آغوش تو، تنها سرزمینیه که می‌خوام شهروندش باشم. 🏞",
    "عشق ما، اون چیزیه که هیچ کس نمی‌تونه ازمون بدزده. 🔒",
    "تو همون آدمی هستی که با تو، هیچ سفری دلهره نداره. 🧳",
    "هر روز که با تو می‌گذره، یه گنج جدید کشف می‌کنم. 💎",
    "تو همون چیزی هستی که قلبم هیچ‌وقت ازش سیر نمی‌شه. 🍷",
    "عشق یعنی توی هر فرم زندگی، تو رو می‌بینم. 🌳",
    "تو یعنی همه‌ی تصمیم‌های خوب من، با تو شروع شدن. ✅",
    "هیچ خیابانی بی تو، آشنا نیست. 🛣",
    "تو همون چیزی هستی که با تو، خونه فقط چهار دیوار نیست. 🏡",
    "عشق ما، اون قصه‌ای هستن که هنوز اوّلشه. 📖",
    "تو همون قسمتی از زندگیم هستی که نمی‌ذارم تموم بشه. 🌹",
    "هر روز با تو، یه عاشقانه‌ی جدیده. 💞",
    "تو همون چیزی هستی که بود و نبودش، تفاوت بین زندگی و زنده بودنه. 🌱",
    "عشق ما، آرومه — مثل قلبی که با ریتم خودش می‌تپه. 🫀",
]


# ---------------------------------------------------------------- English (EN)
EN: list[str] = [
    "You're the home I never have to leave. 🏡💕",
    "The best love stories are still being written. 📖",
    "You're the kind of person poems are about. 🌹",
    "Real love is two hearts beating in the same rhythm. 💓",
    "Every day with you feels like the weekend of my heart. 🌞",
    "Even our silences are music when you're near. 🎶",
    "You stopped being a habit and became my essence. 🌟",
    "Love is always coming back to the same hug, no matter what changes. 🤗",
    "You're the reason I still believe in good things. 💖",
    "The greatest miracle of my life was meeting your eyes on an ordinary day. ✨",
    "Love isn't something you find — it's someone willing to build with you. 🛠💞",
    "Every word I say with you sounds prettier than the last. 🗣️",
    "You're my favorite weather after the storm. 🌧️🌈",
    "Some people are tattooed on your soul — you're one of them. 🖋",
    "Without you, mornings would have no reason to begin. 🌅",
    "You're the thing I thought only existed in movies. 🎬",
    "Love is someone who chooses you, even on bad days. 🌧️💪",
    "I'm giving you my heart — take care of it, it's all I've got. ❤️",
    "You are my smile, even when you're miles away. 😊",
    "No holiday is as restful as one night beside you. 🌙",
    "When I hold your hand, the whole world feels gentler. 🤲",
    "You are the word no language can fully translate. 🤐💞",
    "I won my biggest battles wrapped in your love. 🛡️",
    "Every time I try to describe you, I turn into a poem. 📜",
    "You're the person God whispered to me before I fell asleep. 🙏",
    "Love is two people, one idea, one future. 🌱",
    "Some people live in your memories; you live in my breath. 🌬️",
    "You're nothing like anyone, and you let me miss no one. 💗",
    "Love is having you when there's no one — and feeling the world is here when you are. 🌍",
    "I found you, and the rest of my life is just explaining itself. 🧩",
    "Each day with you opens a new chapter of my book. 📚",
    "Love is when you don't have to perform. 🎭❌",
    "When you laugh, the world warms by five degrees. ☀️",
    "You're the poem that lived in me before I was born. 📝",
    "They say home is where the heart is — my heart is you. 🏠",
    "You weren't a 'choice', you were a necessary event in my life. ⚡",
    "The older I grow, the more I see you were life's quiet best gift. 🌷",
    "Love is opening your eyes in the morning and feeling like you've won. 🏆",
    "Loving you is like breathing — automatic, but vital. 💨💖",
    "We share a secret language with no words. 🤫",
    "Even hours of waiting taste sweet when they're for you. ⏳",
    "You are the kind of person I never want to take for granted. 🌟",
    "The clearest address my heart can give is your name. 📍",
    "Love is 'stay' — even with no reason, you're there. 🌹",
    "You are something the rest of the world can never copy. 🪞",
    "If I had one sentence to say: 'I'm glad you exist.' 💞",
    "You filled an emptiness I didn't know my heart had. 🧡",
    "I tell you 'I love you' every day — because every day I love you more. 🔁",
    "I want to be with you until the end, even when 'end' means nothing. ♾️",
    "You are home, refuge, and every soft place a heart can rest. 🏡",
    "Love is finding one person in a crowd with your eyes closed. 👁️‍🗨️",
    "You're the peace I'd been chasing for years. 🕊️",
    "However far the distance, my heart knows how to find you. 💌",
    "You're the best thing I gathered from all my losses. 🌻",
    "When you're near, even gray days take on color. 🎨",
    "We don't end side by side — we just discover new shapes of love. 🔄",
    "You're the version of life I never want to erase. 💾",
    "Whatever you do, you take love a step higher. 🪜",
    "You're the 2 a.m. smile no one sees but everything holds onto. 🌙",
    "The best feeling in the world is the safety of your hug. 🛡️",
    "Love is never being alone, even when you are. 👫",
    "You're not the 'missing half' — you're the part I didn't know I'd lost. 🧭",
    "If the world ends tomorrow, my last act will be hugging you. 🤗",
    "When I hear your breath, the world becomes wiser. 🫁",
    "Love means no day feels like the one before. 🌅🌄",
    "You're the memory I refuse to let fade. 📷",
    "Whatever happens in my life, I'll thank God for you. 🙏",
    "With you, every season feels like spring. 🌸",
    "I open my eyes in the morning just to see you. 👀",
    "Our love isn't what we show the world — it's what's only ours. 🔐",
    "You're the person whose even arguments are wrapped in kindness. 💕",
    "Some nights I sleep just by thinking of you. ✨",
    "You are my 'reason for today'. 🌟",
    "Love is you holding my hand when no one believes me. 🫂",
    "Every breath I take is one step closer to you. 💨💞",
    "You're the future I would have waited lifetimes for. 🕯",
    "Our love is a letter I'll never delete. 💌",
    "Since you, even my tiredness tastes sweet. 🍯",
    "You're the kind who understands without words. 🤫💕",
    "No words warm a heart like your gaze does. 🔥",
    "Together we're not two — we're one person with two hearts. 💞",
    "Loving you means I'll do anything to protect this. 🛡️❤️",
    "Love is seeing your weaknesses and loving you more. 💖",
    "You're a part of me I didn't know until I met you. 🪞",
    "Every time I see you, my heart falls fresh in love. 💘",
    "I want to love every future version of you. 📅",
    "You're the lost poem I'd been chasing since childhood. 📜",
    "Love is no 'ifs', no 'buts' — just you. ❤️",
    "Every day isn't the first time I love you — it's a day I love you more. 🔄",
    "I have you, which means I have everything. 🌍",
    "Your arms are the only place all the world's wars end. 🕊️",
    "When I think of you, my whole world turns colorful. 🌈",
    "Love means every question of my life has the same answer: you. 🙌",
    "You're what I'd choose infinitely. ♾️",
    "No goodbye with you is the final goodbye. 👋💕",
    "You apologize for my sleepless nights, but you're the moon of them. 🌜",
    "Our love is like a classical song — the more you listen, the deeper it gets. 🎼",
    "You don't have to be special — you are specialness itself. 💎",
    "They say everyone has a half — you don't complete me, you complete the *idea* of me. 🧩",
    "My greatest happiness is the most ordinary moments with you. ☕",
    "You're the story I want to be in until the last page. 📖",
    "No voice trembles my heart like your 'I love you'. 🎙",
    "You are every good tomorrow I look forward to. 🌤️",
    "Our love is a beautiful secret between us and God. 🤲",
    "Even the simplest mornings feel miraculous with you. ☕",
    "You're the one my heart loved without asking me. 💓",
    "If love had a color, it would be the color of your eyes. 👁",
    "You are the song of my heart that never ends. 🎵",
    "I set all my clocks by you. ⏰",
    "I don't know how I lived before you — maybe I didn't, maybe I was just alive. 🌱",
    "You're the excuse I have to wake up every morning. 🌅",
    "No clock or calendar can measure us. ⌛",
    "You are the answer to all my prayers. 🤲",
    "When you're near, even silence fills up in its own way. 🤫",
    "You are my heart's permanent address. 🏠",
    "Love is dreaming while awake. 💭",
    "No book is as readable as your eyes. 📚",
    "You're the thing I do with all of myself. 💪",
    "Our love is calm — like the sea before sunrise. 🌊",
    "You're the person who makes even defeat look beautiful. 🏵",
    "Finding you each day is a fresh chance at life. 🍀",
    "You're the happy ending of my story. 🎬",
    "Love is you making me laugh on my worst days. 😂",
    "Together we built a tiny world no one else can enter. 🔐",
    "You're what I don't want to become routine — stay new. 🌷",
    "Love is finding a fresh reason to stay every day. 📌",
    "If my heart could talk, it would only say your name. 💗",
    "You're what I want to protect with everything I have. 🛡",
    "Every thought of you warms something inside me. 🔥",
    "You're the reason for my smiles without reason. 😊",
    "If the world is to end, I want the last thing I see to be your eyes. 👁",
    "Love is two people making silence enjoyable together. 🤍",
    "You're the poem I read before I sleep. 📖",
    "Your hug is the only safe land in an unsafe world. 🤗",
    "You're the beautiful dream I never want to wake from. 💤",
    "Without you, no word is complete — not even 'I'. 🔤",
    "Together we are a song people dance to. 🎵",
    "You're my 'every day' — repeated and precious. 🌞",
    "Love means creating happiness instead of chasing it. ✨",
    "You made the world I see turn colorful. 🎨",
    "Without you, the future is just a date; with you, it's a story. 📅",
    "You are the last line of a story I never want to finish. ✍️",
    "Each time I hold your hand, everything settles into place. 🤝",
    "Our love is a calm no book ever found. 📕",
    "You're the person God hid from me until I could appreciate you. 🙏",
    "Every day with you is a step toward the best version of myself. 🚶‍♀️",
    "You're the best question my heart keeps asking. 🌀",
    "If the world is a puzzle, you're the last piece that finally fits. 🧩",
    "When you laugh, my heart gets louder. 💓",
    "You're the person who makes even sadness bearable. 🌧",
    "No journey is as exciting as the one to your heart. 🧳",
    "We share a wordless language. 🤐💞",
    "Love is learning from each other every day. 📚",
    "You're what no wish can hold. 🌠",
    "If loving is a crime, I'm the world's greatest criminal. 🚔💖",
    "The more I think of you, the warmer my heart grows. 🔥",
    "With you, I don't fear tomorrow — every tomorrow is a gift. 🎁",
    "Our love is something even time can't decay. ⏳",
    "You're the poem I refuse to show anyone. 📜",
    "Each time you smile at me, a flower blooms in my chest. 🌹",
    "You're the one with whom no day repeats. 🌈",
    "Love is no silence between us being empty. 🤍",
    "You're the 'maybe' that became 'definitely'. ✅",
    "Every time I say your name, it feels like a prayer. 🤲",
    "You're the part of my life I never want to rewrite. ✍️",
    "Your hug is the only place my heart truly rests. 🏡",
    "Without you, even spring feels like autumn. 🍂",
    "You're the answer God prepared before I asked. 🙏",
    "Love means no day is complete without you. 🌗",
    "You're a small world inside the bigger world. 🌍",
    "Every time I see you, it feels like the first time. 👀",
    "You're the one my heart trusted before I understood why. 💝",
    "No one understands our love — that's the most beautiful part. 🤫",
    "You're the happiness I earned through all my patience. ⏳💕",
    "No sleepless night is tiring when I'm thinking of you. 🌙",
    "You're the one my heart said yes to without asking. ✅",
    "Love is you being beautiful in my worst days. 🌷",
    "You're the reason all my tomorrows have hope. 🌟",
    "No painting is as colorless-yet-beautiful as your face. 🎨",
    "You're someone no description ever does justice to. 📖",
    "Our love is the world's quiet part, heard only by us. 🤫💕",
    "You're what I asked God for a thousand times. 🤲",
    "Every hug of yours melts a piece of my longing. 🤗",
    "You're the poem my heart writes without a pen. 🖋",
    "Our love has no single color — it carries them all. 🌈",
    "You mean every time I miss you, I have a map back. 🗺",
    "Whatever I do, you walk with me — even when you're gone. 👤",
    "You're the sweetness no other sweetness compares to. 🍯",
    "Peace means resting my head on your shoulder. 😌",
    "Love is your presence in every chapter of my life. 📊",
    "You're the one who made life meaningful. 📌",
    "There's no end for us — only fresh beginnings. 🔁",
    "You're the one I'll never get used to — you stay new. 🌷",
    "Our love is a classic book — each read reveals something new. 📚",
    "You mean every good day of mine is a day with you. 🌞",
    "Every time your hand is in mine, I hold the whole world. 🌍",
    "You're the one my heart found in the crowd. 💗",
    "Love is listening even in silence. 🎧",
    "You're what I never want variety from. 💫",
    "I discover a new 'I love you' every day. 📝",
    "You're the one who touched my soul without trying. ✨",
    "Our love is the part of my story nothing else can erase. 🖋",
    "You're the one with whom even waiting is sweet. ⏳",
    "Without you, my days are white — you are my color. 🎨",
    "You mean every thought of you makes the world kinder. 🌍💞",
    "Our love is what no word can describe — we just feel it. 💕",
    "You are the answer to all my 'why's. ❓",
    "Each morning, my first thought is your name. 🌅",
    "You are a star I have even in the darkest nights. ⭐",
    "Your hug is the only nation I want to be a citizen of. 🏞",
    "Our love is what no one can steal from us. 🔒",
    "You're the one with whom no journey feels uncertain. 🧳",
    "Every day with you, I discover a new treasure. 💎",
    "You're the one my heart never tires of. 🍷",
    "Love is seeing you in every shape of life. 🌳",
    "You mean every good decision of mine started with you. ✅",
    "No street is familiar without you. 🛣",
    "You're the one who makes a home more than four walls. 🏡",
    "Our love is a story still at its beginning. 📖",
    "You're the part of my life I refuse to end. 🌹",
    "Every day with you is a brand-new love story. 💞",
    "You're what makes the difference between living and being alive. 🌱",
    "Our love is calm — like a heart beating its own rhythm. 🫀",
]


assert len(FA) >= 200, f"Persian quotes underfilled: {len(FA)}"
assert len(EN) >= 200, f"English quotes underfilled: {len(EN)}"
